version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:851725377005:task-definition/api-repository"
        LoadBalancerInfo:
          ContainerName: "handson-torii-api"
          ContainerPort: 80