version: 0.2
env:
  variables:
    ECR_REPO_NAME: api-repository
phases:
  pre_build:
    commands:
      - echo "hello"
      
      #ECR login
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}

      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
  build:
    commands:
      - docker build -t ${ECR_REPO_NAME}:latest .
  post_build:
    commands:
      - docker tag ${ECR_REPO_NAME}:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}

artifacts:
  files:
    - imagedefinitions.json

# version: 0.2
# env:
#   variables:
#     AWS_DEFAULT_REGION: "ap-northeast-1"
#     DOCKER_USER: AWS
#     ECR_MAIN_URI: "851725377005.dkr.ecr.ap-northeast-1.amazonaws.com"
#     ECR_REPO_NAME: api-repository
#     IMAGE_TAG: latest 

# phases:
#   pre_build:
#     commands:
#       - echo "ECRへログイン"
#       - aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login --username ${DOCKER_USER} --password-stdin ${ECR_MAIN_URI}
#   build:
#     commands:
#       - echo "ビルド開始"
#       - docker build -t "${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest" .
#   post_build:
#     commands:
#       - echo "ECRへpush"
#       - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:${CODEBUILD_RESOLVED_SOURCE_VERSION:0:8}"
#       - docker tag ${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest ${ECR_IMAGE_URI}
#       - docker push "${ECR_IMAGE_URI}"

#       - printf '{"ImageURI":"%s"}' ${ECR_IMAGE_URI} > imageDetail.json
# artifacts:
#   files: 
#     - imageDetail.json
#     - appspec.yml
#     - taskdef.json

